list p=16f84a
include <p16f84.inc>

__CONFIG _CP_OFF&_WDT_OFF&_PWRTE_ON&_XT_OSC

#define posiciones .20 ; posiciones a ocupar en la RAM
#define inicial 0x27 ; Primera dirección a almacenar

PRIMER_NUMERO EQU 0x20
SEGUNDO_NUMERO EQU 0x21
RESULTADO_NUMERO EQU 0x22
CAMBIO_DE_NUMERO equ 0x23

org 0x00 ; Posición de memoria de prog. que comienza

Inicio 
	BSF STATUS, RP0
	CLRF TRISA
	CLRF PORTA
	MOVLW B'11111111'
	MOVWF TRISA

	clrf TRISB
	clrf PORTB
	MOVLW B'00000000'
	MOVWF PORTB
	BCF STATUS, RP0

	MOVLW B'00000000'
	MOVWF PORTB

;------------------- ESCRITURA -------------------	

	movlw .1
	movwf CAMBIO_DE_NUMERO
	CLRW
	movwf PRIMER_NUMERO
	movwf SEGUNDO_NUMERO
	movwf RESULTADO
	movlw inicial-1
	movwf FSR ; puntero = posición anterior a la inicial


	call START

;------------------------ PULSADORES --------------------
START
	
	CALL PULSADOR_UNO

	CALL PULSADOR_DOS
	
	CALL PULSADOR_CUATRO
	
	CALL PULSADOR_OCHO

	CALL PULSADOR_NUEVO_NUM

	CALL PULSADOR_RESULTADO
	
	GOTO START


PULSADOR_UNO
	BTFSC PORTA,0 ;PULSADORADELANTE ;(PORTA, 0) 
	;CALL UNO_NUM
	GOTO UNO
	RETURN

PULSADOR_DOS
	BTFSC PORTA,1 ;STOP ;(PORTA, 1) 
	GOTO DOS	
	RETURN 

PULSADOR_CUATRO
	BTFSC PORTA,2 ;PULSADORRETROCEDER ;(PORTA, 2) 
	GOTO CUATRO
	RETURN

PULSADOR_OCHO
	BTFSC PORTA,3 ;PULSADORDERECHA ;(PORTA, 3) 
	GOTO OCHO
	RETURN

PULSADOR_NUEVO_NUM
	BTFSC PORTA,4  ;PULSADORIZQUIERDA ;(PORTA, 4)  
	GOTO NUEVO_SUMA
	RETURN

PULSADOR_RESULTADO
	BTFSC PORTB,5 ;PULSADORCOMENZAR ; (PORTB, 1) 
	GOTO RESULTADO
	RETURN

;------------------------- MANEJO DE SUMAS DE LOS NÚMEROS ------------------------------

UNO_NUM
;	BTFSC CAMBIO_DE_NUMERO,1
 	GOTO UNO
	GOTO UNO_SEGUNDO
	RETURN

DOS_NUM
;	BTFSC CAMBIO_DE_NUMERO
 	GOTO DOS
	GOTO DOS_SEGUNDO
	RETURN

CUATRO_NUM
;	BTFSC CAMBIO_DE_NUMERO
 	GOTO CUATRO
	GOTO CUATRO_SEGUNDO
	RETURN

OCHO_NUM
;	BTFSC CAMBIO_DE_NUMERO
 	GOTO OCHO
	GOTO OCHO_SEGUNDO
	RETURN


; -------------------- MANEJO DE SUMAS PRIMER NUMERO ------------------------------------
UNO
	BTFSC PORTA,0
	GOTO UNO

	incf FSR
	movwf INDF 

	 movlw .1 
	 addwf PRIMER_NUMERO,PRIMER_NUMERO ; PRIMER_NUMERO = PRIMER_NUMERO + W 
	 movwf PRIMER_NUMERO ; RES1 = 5 

	RETURN

DOS
	BTFSC PORTA,1
	GOTO DOS

	incf FSR 
	movwf INDF 

	movlw .2 
	addwf PRIMER_NUMERO,PRIMER_NUMERO 
 	movwf PRIMER_NUMERO 

	RETURN

CUATRO
	BTFSC PORTA,2
	GOTO CUATRO

	incf FSR ; Apunta a la siguiente posición
	movwf INDF ; Dato --> INDF	decf NUMERO
 
	movlw .4 
	addwf PRIMER_NUMERO,PRIMER_NUMERO
 	movwf PRIMER_NUMERO  

	RETURN

OCHO
	BTFSC PORTA,3
	GOTO OCHO

	incf FSR 
	movwf INDF 
 
	movlw .8 
	addwf PRIMER_NUMERO,PRIMER_NUMERO
 	movwf PRIMER_NUMERO  
	RETURN


; -------------------- MANEJO DE SUMAS SEGUNDO NUMERO ------------------------------------
UNO_SEGUNDO
	BTFSC PORTA,0
	GOTO UNO

	incf FSR
	movwf INDF 

	movlw .1 
	addwf SEGUNDO_NUMERO,SEGUNDO_NUMERO 
	movwf SEGUNDO_NUMERO  
	RETURN

DOS_SEGUNDO
	BTFSC PORTA,1
	GOTO DOS

	incf FSR 
	movwf INDF 

	movlw .2 
	addwf SEGUNDO_NUMERO,SEGUNDO_NUMERO 
	movwf SEGUNDO_NUMERO  
	RETURN

CUATRO_SEGUNDO
	BTFSC PORTA,2
	GOTO CUATRO

	incf FSR ; Apunta a la siguiente posición
	movwf INDF ; Dato --> INDF	decf NUMERO
 
	movlw .4 
	addwf SEGUNDO_NUMERO,SEGUNDO_NUMERO 
	movwf SEGUNDO_NUMERO
	RETURN

OCHO_SEGUNDO
	BTFSC PORTA,3
	GOTO OCHO

	incf FSR 
	movwf INDF 
 
	movlw .8 
	addwf SEGUNDO_NUMERO,SEGUNDO_NUMERO 
	movwf SEGUNDO_NUMERO 
	RETURN

; -------------------------- CAMBIO DE NÚMERO -------------------

NUEVO_SUMA
	BTFSC PORTA,4
	GOTO NUEVO_SUMA
	
	movlw .0 
	movwf SEGUNDO_NUMERO ; CAMBIA LA BANDERA PARA ALMACENAR EN EL SEGUNDO NUMERO

	RETURN

RESULTADO
	BTFSC PORTB,5
	GOTO RESULTADO
	
	movf PRIMER_NUMERO,W ; W = NUMERO
	MOVWF PORTB

	RETURN

END